# Generated by Django 5.2.4 on 2025-08-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.CharField(max_length=50, null=True, verbose_name='Wilaya'),
        ),
    ]
