version: '3.9'

services:
  backend:
    build: ./Backend
    image: hvmc-backend
    container_name: hvmc_backend
    env_file: .env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - USE_X_FORWARDED_HOST=1
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    networks:
      - hvmc-network
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: hvmc_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env.prod
    environment:
      POSTGRES_DB: hvmc_prod
      POSTGRES_USER: hvmc_user
      POSTGRES_PASSWORD: strong-password
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
    networks:
      - hvmc-network
    restart: unless-stopped

  frontend:
   build:
    context: ./hvmc-store
    dockerfile: Dockerfile
    args:
      - VITE_API_URL=${VITE_API_URL:-/fr/api}
   container_name: hvmc_frontend
   volumes:
    - frontend_dist:/app/dist  # Changed to /app/dist to match build location
   networks:
    - hvmc-network
   restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: hvmc_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/ecommerce.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro  # This mounts the built assets
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - hvmc-network
    restart: unless-stopped

volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_dist:
    driver: local
    driver_opts:
      type: none
      device: ./hvmc-store/dist  # Relative to compose file
      o: bind

networks:
  hvmc-network:
    driver: bridge