version: '3.9'

services:
  backend:
    build: ./Backend
    image: hvmc-backend
    container_name: hvmc_backend
    env_file: .env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - hvmc-network
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: hvmc_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env.prod
    environment:
      POSTGRES_DB: hvmc_prod
      POSTGRES_USER: hvmc_user
      POSTGRES_PASSWORD: strong-password
    networks:
      - hvmc-network
    restart: unless-stopped

  frontend:
    build:
      context: ./hvmc-store
      dockerfile: Dockerfile
    image: hvmc-frontend
    container_name: hvmc_frontend
    networks:
      - hvmc-network
    ports:
      - "3000:80"  # map nginx port 80 to host 3000 (change if you want)
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: hvmc_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/ecommerce.conf:/etc/nginx/conf.d/ecommerce.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - hvmc-network
    restart: unless-stopped

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  hvmc-network:
    driver: bridge
