version: '3.9'

services:
  backend:
    build: ./Backend
    image: hvmc-backend
    container_name: hvmc_backend
    env_file: .env.prod
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - hvmc-network
    restart: unless-stopped

  frontend:
    build: ./hvmc-store 
    image: hvmc-frontend
    container_name: hvmc_frontend
    ports:
    - "5173:5173"  # Add this for Vite HMR in development
    networks:
      - hvmc-network
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: hvmc_db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env.prod
    networks:
      - hvmc-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: hvmc_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
      - media_volume:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - hvmc-network
    restart: unless-stopped

volumes:
  pg_data:
  static_volume:
  media_volume:

networks:
  hvmc-network:
    driver: bridge